# Default values for goodcoin-fe.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: goodcoin/app
  tag: client
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /
  hosts:
    - good-coin.org
  tls: []

resources:
  limits:
    cpu: 0.1
    memory: 256Mi
  requests:
    cpu: 0.1
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
