apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-rds
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8s-rds
  template:
    metadata:
      labels:
        name: k8s-rds
    spec:
      containers:
      - image: sorenmat/k8s-rds:latest
        env:
        - name: AWS_REGION
          value: {{ .Values.aws_region }}
        - name: AWS_ACCESS_KEY_ID
          value: {{ .Values.aws_access_key_id }}
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ .Values.aws_secret_access_key }}
        imagePullPolicy: Always
        name: k8s-rds
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: k8s-rds-operator
