apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "goodcoin-be.fullname" . }}
  labels:
    app: {{ template "goodcoin-be.name" . }}
    chart: {{ template "goodcoin-be.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "goodcoin-be.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "goodcoin-be.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: "80"
            - name: DB_USER
              value: "{{ .Values.database.user }}"
            - name: DB_HOST
              value: "{{ .Values.database.host }}"
            - name: DB_SCHEME
              value: "{{ .Values.database.scheme }}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "goodcoin-be.fullname" . }}-secret
                  key: dbpassword
            - name: DB_PORT
              value: "{{ .Values.database.port }}"
            - name: FRONT_URL
              value: "http://good-coin.org"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            tcpSocket:
              port: 80
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            tcpSocket:
              port: 80
          resources:
{{ toYaml .Values.resources | indent 12 }}
