apiVersion: v1
kind: Secret
metadata:
  name: {{ template "goodcoin-be.fullname" . }}-secret
type: Opaque
data:
  {{ if .Values.dbpassword }}
  dbpassword: {{ .Values.dbpassword | b64enc | quote }}
  {{- end }}
