version: 2.1

references:

base_image: &base_image
  goodcoin/circleci:latest

working_directory: &working_directory
  ~/project

default_config: &default_config
  docker:
    - image: *base_image
  working_directory: *working_directory


jobs:
  build:
    <<: *default_config
    steps:
      - checkout
      - run:
          name: Run tests using pre-commit
          command: |
            pre-commit install
            pre-commit run --all-files

  terraform_plan:
    <<: *default_config
    steps:
      - checkout
      - run:
          name: terraform plan s3_bucket
          command: |
            cd ~/project/terraform/s3
            /bin/bash init.sh
            terraform plan
      - run:
          name: terraform plan route53
          command: |
            cd ~/project/terraform/route53
            /bin/bash init.sh
            terraform plan
      - run:
          name: terraform plan vpc
          command: |
            cd  ~/project/terraform/vpc
            /bin/bash init.sh
            terraform plan
      - run:
          name: terraform plan eks
          command: |
            cd  ~/project/terraform/eks
            /bin/bash init.sh
            terraform plan

  terraform_apply_route53:
    <<: *default_config
    steps:
      - checkout
      - run:
          name: terraform apply route53
          command: |
            cd terraform/route53
            /bin/bash init.sh
            terraform apply --auto-approve

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - terraform_plan:
          requires:
            - build
      - hold:
          filters:
            branches:
              only: master
          type: approval
          requires:
            - terraform_plan
      - terraform_apply_route53:
          filters:
            branches:
              only: master
          requires:
            - hold
