version: 2.1

references:

terraform_working_directory: &tf_working_directory
  ~/terraform

jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "hello world"

  terraform_lint:
    docker:
      - image: wata727/tflint
    working_directory: *tf_working_directory
    steps:
      - checkout
      - run: find . -type f -name \*tf -exec dirname {} \; | sort -u | while read foldername; do tflint $foldername; done

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - terraform_lint:
          requires:
            - build

