version: 2.1

references:

base_image: &base_image
  goodcoin/circleci:latest

working_directory: &working_directory
  ~/project

default_config: &default_config
  docker:
    - image: *base_image
  working_directory: *working_directory


jobs:
  build:
    <<: *default_config
    steps:
      - checkout
      - run:
          name: Run tests using pre-commit
          command: |
            pre-commit install
            pre-commit run --all-files

  terraform_plan:
    <<: *default_config
    steps:
      - checkout
      - run:
          name: terraform plan s3_bucket
          command: |
            cd ~/project/terraform/s3
            /bin/bash init.sh
            terraform plan
      - run:
          name: terraform plan route53
          command: |
            cd ~/project/terraform/route53
            /bin/bash init.sh
            terraform plan
      - run:
          name: terraform plan vpc
          command: |
            cd  ~/project/terraform/vpc
            /bin/bash init.sh
            terraform plan

  terraform_apply_infrastructure:
    <<: *default_config
    steps:
      - checkout
      - run:
          name: terraform apply s3
          command: |
            cd ~/project/terraform/s3
            /bin/bash init.sh
            terraform apply --auto-approve
      - run:
          name: terraform apply vpc
          command: |
            cd ~/project/terraform/vpc
            /bin/bash init.sh
            terraform apply --auto-approve
      - run:
          name: terraform apply route53
          command: |
            cd terraform/route53
            /bin/bash init.sh
            terraform apply --auto-approve

  terraform_plan_eks:
    <<: *default_config
    steps:
      - checkout
      - run:
          name: terraform plan eks
          command: |
            cd  ~/project/terraform/eks
            /bin/bash init.sh
            terraform plan

  terraform_apply_eks:
    <<: *default_config
    steps:
      - checkout
      - run:
          name: terraform apply eks
          command: |
            cd ~/project/terraform/eks
            /bin/bash init.sh
            terraform apply --auto-approve

  helm_install_charts:
    <<: *default_config
    steps:
      - checkout
      - run:
          name: create kubectl config
          command: |
            aws eks --region us-east-1 update-kubeconfig --name goodcoin-eks-spot
      - run:
          name: deploy controllers 
          command: |
            cd ~/project/kubernetes/charts
            helm upgrade ingress-nginx ingress-nginx --install --force
            helm upgrade k8s-rds k8s-rds --set aws_region=$AWS_DEFAULT_REGION --set aws_access_key_id=$AWS_ACCESS_KEY_ID --set aws_secret_access_key=$AWS_SECRET_ACCESS_KEY --install --force
      - run:
          name: create secret for docker login
          command: |
            kubectl create secret docker-registry regcred --docker-server=$DOCKER_SERVER --docker-username=$DOCKER_USERNAME --docker-password="${DOCKER_PASSWORD}"
      - run:
          name: deploy application
          command: |
            cd ~/project/kubernetes/charts
            kubectl create namespace goodcoin
            helm upgrade goodcoin-db goodcoin-db --namespace goodcoin --install --force
            helm upgrade goodcoin-be goodcoin-be --namespace goodcoin --install --force
            helm upgrade goodcoin-fe goodcoin-fe --namespace goodcoin --install --force

  helm_destroy_charts:
    <<: *default_config
    steps:
      - checkout
      - run:
          name: create kubectl config
          command: |
            aws eks --region eu-west-1 update-kubeconfig --name goodcoin-eks-spot
      - run:
          name: destroy application
          command: |
            cd ~/project/kubernetes/charts
            helm delete --purge goodcoin-db --namespace goodcoin
            helm delete --purge goodcoin-be --namespace goodcoin
            helm delete --purge goodcoin-fe --namespace goodcoin
      - run:
          name: destroy controllers
          command: |
            cd ~/project/kubernetes/charts
            helm delete --purge ingress-nginx
            helm delete --purge k8s-rds

  terraform_destroy_eks:
    <<: *default_config
    steps:
      - checkout
      - run:
          name: terraform destroy eks
          command: |
            cd ~/project/terraform/eks
            /bin/bash init.sh
            terraform destroy --auto-approve

  terraform_destroy_infrastructure:
    <<: *default_config
    steps:
      - checkout
      - run:
          name: terraform destroy s3
          command: |
            cd ~/project/terraform/s3
            /bin/bash init.sh
            terraform destroy --auto-approve
      - run:
          name: terraform destroy vpc
          command: |
            cd ~/project/terraform/vpc
            /bin/bash init.sh
            terraform destroy --auto-approve
      - run:
          name: terraform destroy route53
          command: |
            cd terraform/route53
            /bin/bash init.sh
            terraform destroy --auto-approve

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - terraform_plan:
          requires:
            - build
      - hold_terraform:
          filters:
            branches:
              only: master
          type: approval
          requires:
            - terraform_plan
      - terraform_apply_infrastructure:
          filters:
            branches:
              only: master
          requires:
            - hold_terraform
      - terraform_plan_eks:
          requires:
            - terraform_apply_infrastructure
      - hold_eks:
          filters:
            branches:
              only: master
          type: approval
          requires:
            - terraform_apply_infrastructure
      - terraform_apply_eks:
          filters:
            branches:
              only: master
          requires:
            - hold_eks
      - helm_install_charts:
            filters:
              branches:
                only: master
            requires:
              - terraform_apply_eks

  terminate:
    jobs:
      - hold_destroy_eks:
          filters:
            branches:
              only: master
            tags:
              only:
                - destroy-eks
                - destroy-all
          type: approval
      - helm_destroy_charts:
          filters:
            branches:
              only: master
            tags:
              only:
                - destroy-eks
                - destroy-all
          requires:
            - hold_destroy_eks
      - terraform_destroy_eks:
          filters:
            branches:
              only: master
            tags:
              only:
                - destroy-eks
                - destroy-all
          requires:
            - helm_destroy_charts
      - hold_destroy_infrastructure:
          filters:
            branches:
              only: master
            tags:
              only: destroy-all
          type: approval
          requires:
            - terraform_destroy_eks
      - terraform_destroy_infrastructure:
          filters:
            branches:
              only: master
            tags:
              only: destroy-all
          requires:
            - hold_destroy_infrastructure
