apiVersion: v1
kind: Secret
metadata:
  name: {{ template "goodcoin-db.fullname" . }}-secret
type: Opaque
data:
  {{ if .Values.password }}
  dbpassword: {{ .Values.password | b64enc | quote }}
  {{- end }}
